### ISSUE TITLE
How about CI tools?

### ISSUE THREAD

**Issue by willmedtrainingsolutionscom** [diegocard/awesome-html5#10]
If you are recommending that HTML be developed and collaborated on using GitHub then perhaps recommendation of Continuous Integration tools is in scope for this list.

One such project is https://github.com/fulldecent/web-puc, it checks your `<link href="...` tags to see if they are pointing to the latest version of a thing. I am sure there are other great tools out there. And I'd love to add them to my CI tools.

**Comment by diegocard** [comment]
This was added a long time ago for this project, but thanks for the suggestion.
